---
title: "DTSA-5301 Final Project"
output: html_document
date: "2022-10-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)

url_head = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_"

url_tails = c("confirmed_US.csv", "confirmed_global.csv", "deaths_US.csv", "deaths_global.csv")

urls = str_c(url_head, url_tails)
```

```{r import}
cases_us_csv = read_csv(urls[1], show_col_types = FALSE)
cases_global_csv = read_csv(urls[2], show_col_types = FALSE)
deaths_us_csv = read_csv(urls[3], show_col_types = FALSE)
deaths_global_csv = read_csv(urls[4], show_col_types = FALSE)
```

```{r tidy}
deaths_global = pivot_longer(deaths_global_csv, cols = -c(`Province/State`, `Country/Region`, Lat, Long), names_to="date", values_to = "deaths") %>% select(-c(Lat, Long))

cases_global = pivot_longer(cases_global_csv, cols = -c(`Province/State`, `Country/Region`, Lat, Long), names_to="date", values_to = "deaths") %>% select(-c(Lat, Long))

deaths_us = deaths_us_csv %>% select(-c(Population, Admin2, Lat, Long_, UID, iso2, iso3, code3, FIPS, Country_Region, Combined_Key))
deaths_us = pivot_longer(deaths_us, cols = -c(`Province_State`), names_to="date", values_to = "deaths")
deaths_us$date = mdy(deaths_us$date)

cases_us = deaths_us_csv %>% select(-c(Population, Admin2, Lat, Long_, UID, iso2, iso3, code3, FIPS, Country_Region, Combined_Key))
cases_us = pivot_longer(cases_us, cols = -c(`Province_State`), names_to="date", values_to = "cases")
cases_us$date = mdy(cases_us$date)
```


```{r session info}
sessionInfo()
```

